title: 被认知圈养
description: 探索认知的边界，突破思维的牢笼
baseurl: ""
url: ""

# 多语言设置
#languages: ["zh", "en"]
#default_lang: "zh"
#exclude_from_localization: ["assets", "images"]
#parallel_localization: true

# 构建设置
markdown: kramdown
permalink: /:year/:month/:day/:title/

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/

# 插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
#  - jekyll-multiple-languages-plugin

# 默认布局
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# 主题设置
theme:
  primary_color: "#2c3e50"
  secondary_color: "#34495e"
  accent_color: "#3498db"
  text_color: "#333333"
  background_color: "#ffffff"
  font_family: "Noto Sans SC, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif" 